##coding=utf8
##date=2014-08-17
##author=sanhe
data = \
{
    "Adherence to Antipsychotic Medications for Individuals With Schizophrenia (SAA) - Administrative Specification": {
        "step 1": "Identify the IPSD. The IPSD is the earliest dispensing event for any antipsychotic medication (Table SAA-A; Long-Acting Injections 14 Days Supply Value Set; Long-Acting Injections 28 Days Supply Value Set) during the measurement year.",
        "step 2": "To determine the treatment period, calculate the number of days from the IPSD (inclusive) to the end of the measurement year.",
        "step 3": "Count the days covered by at least one antipsychotic medications (Table SAA-A; Long-Acting Injections 14 Days Supply Value Set; Long-Acting Injections 28 Days Supply Value Set) during the treatment period. To ensure that days supply that extend beyond the measurement year are not counted, subtract any days supply that extends beyond December 31 of the measurement year.",
        "step 4": "Calculate the member\u2019s PDC using the following equation. Round to two decimal places, using the .5 rule.\nTotal Days Covered by an Antipsychotic Medication in the Treatment Period (step 3)\nTotal Days in Treatment Period (step 2)",
        "step 5": "Sum the number of members whose PDC is \u226580% for their treatment period."
    },
    "Adherence to Antipsychotic Medications for Individuals With Schizophrenia (SAA) - Eligible Population": {
        "step 1": "Identify members with schizophrenia as those who met at least one of the following criteria during the measurement year:\n\u2022\tAt least one acute inpatient encounter with any diagnosis of schizophrenia. Either of the following code combinations meets criteria:\n\u2013\tBH Stand Alone Acute Inpatient Value Set with Schizophrenia Value Set.\n\u2013\tBH Acute Inpatient Value Set with BH Acute Inpatient POS Value Set and Schizophrenia Value Set.\n\u2022\tAt least two visits in an outpatient, intensive outpatient, partial hospitalization, ED or nonacute inpatient setting, on different dates of service, with any diagnosis of schizophrenia. Any two of the following code combinations meet criteria:\n\u2013\tBH Stand Alone Outpatient/PH/IOP Value Set with Schizophrenia Value Set.\n\u2013\tBH Outpatient/PH/IOP Value Set with BH Outpatient/PH/IOP POS Value Set and Schizophrenia Value Set.\n\u2013\tED Value Set with Schizophrenia Value Set.\n\u2013\tBH ED Value Set with BH ED POS Value Set and Schizophrenia Value Set.\n\u2013\tBH Stand Alone Nonacute Inpatient Value Set with Schizophrenia Value Set.\n\u2013\tBH Nonacute Inpatient Value Set with BH Nonacute Inpatient POS Value Set and Schizophrenia Value Set.",
        "step 2": "Required exclusions\tExclude members who met at least one of the following during the measurement year.\n\u2022\tA diagnosis of dementia (Dementia Value Set).\n\u2022\tDid not have at least two antipsychotic medication dispensing events, with at least one of the events occurring on or between January 1 and September 30. There are two ways to identify dispensing events: by claim/encounter data and by pharmacy data. The organization must use both methods to identify dispensing events, but an event need only be identified by one method to be counted.\n\u2013\tClaim/encounter data. An antipsychotic medication (Long-Acting Injections 14 Days Supply Value Set or Long-Acting Injections 28 Days Supply Value Set).\n\u2013\tPharmacy data. Dispensed an antipsychotic medication (Table SAA-A) on an ambulatory basis."
    },
    "Ambulatory Care (AMB) - identify and categorize inpatient discharges": {
        "step 1": "Identify all acute inpatient stays with a discharge date on or between January 1 and December 31 of the measurement year.",
        "step 2": "Exclude discharges with a principal diagnosis of mental health or chemical dependency (Mental and Behavioral Disorders Value Set), a principal diagnosis of live-born infant (Deliveries Infant Record Value Set) or an MS-DRG for mental health, chemical dependency or rehabilitation (IPU Exclusions MS-DRG Value Set).\nExclude newborn care (Newborns/Neonates MS-DRG Value Set) rendered from birth to discharge home from delivery (only include care rendered during subsequent rehospitalizations after the delivery discharge).",
        "step 3": "Report total inpatient, using all discharges identified after completing steps 1 and 2.",
        "step 4": "Report maternity, surgery and medicine using MS-DRGs. For organizations that use DRGs, categorize each discharge as maternity, surgery or medicine.\n\u2022\tMaternity (Maternity MS-DRG Value Set). A delivery is not required for inclusion in the Maternity category; any maternity-related stay is included. Include birthing center deliveries and count them as one day of stay.\n\u2022\tSurgery (Surgery MS-DRG Value Set).\n\u2022\tMedicine:\n\u2013\tMedicine MS-DRG Value Set.\n\u2013\tNewborns/Neonates MS-DRG Value Set. Do not include newborn care rendered from birth to discharge home from delivery; only report newborn care rendered if the baby is discharged home from delivery and is subsequently rehospitalized.\nNote: If reporting using MS-DRGs, Total Inpatient will not equal the sum of Maternity, Surgery and Medicine because DRGs for Principal Diagnosis Invalid as Discharge Diagnosis and Ungroupable are included in Total Inpatient, but are not included in maternity, surgery or medicine.\nIf the organization does not use MS-DRGs, follow steps 5\u20137 to categorize discharges.",
        "step 5": "Report maternity. A delivery is not required for inclusion in the Maternity category; any maternity-related stay is included. Include birthing center deliveries and count them as one day of stay.\nStarting with all discharges identified in step 3, identify maternity using either of the following:\n\u2022\tA maternity-related principal diagnosis (Maternity Diagnosis Value Set).\n\u2022\tA maternity-related stay (Maternity Value Set).",
        "step 6": "Report surgery. From discharges remaining after removing maternity (step 5) from total inpatient (step 3), identify surgery (Surgery Value Set).",
        "step 7": "Report medicine. Categorize as medicine the discharges remaining after removing maternity (step 5) and surgery (step 6) from total inpatient (step 3)."
    },
    "Antidepressant Medication Management (AMM) - Eligible Population": {
        "step 1": "Determine the IPSD. Identify the date of the earliest dispensing event for an antidepressant medication (Table AMM-C) during the Intake Period.",
        "step 2": "Required exclusion\tExclude members who did not have a diagnosis of major depression in an inpatient, outpatient, ED, intensive outpatient or partial hospitalization setting during the 121-day period from 60 days prior to the IPSD, through the IPSD and the 60 days after the IPSD. Members who meet any of the following criteria remain in the eligible population:\n\u2022\tAn outpatient visit, intensive outpatient encounter or partial hospitalization with any diagnosis of major depression. Either of the following code combinations meets criteria:\n\u2013\tAMM Stand Alone Visits Value Set with Major Depression Value Set.\n\u2013\tAMM Visits Value Set with AMM POS Value Set and Major Depression Value Set.\n\u2022\tAn ED visit (ED Value Set) with any diagnosis of major depression (Major Depression Value Set).\n\u2022\tAn inpatient (acute or nonacute) encounter with any diagnosis of major depression (Major Depression Value Set).\nFor an inpatient (acute or nonacute) encounter, use the date of discharge.\nFor a direct transfer, use the discharge date from the facility where the member was transferred.",
        "step 3": "Test for Negative Medication History. Exclude members who filled a prescription for an antidepressant medication 105 days prior to the IPSD.",
        "step 4": "Calculate continuous enrollment. Members must be continuously enrolled for 105 days prior to the IPSD to 231 days after the IPSD."
    },
    "Appropriate Testing for Children With Pharyngitis (CWP) - Eligible Population": {
        "step 1": "Identify all members who had an outpatient visit (Outpatient Value Set), an observation visit (Observation Value Set) or an ED visit (ED Value Set) during the intake period, with only a diagnosis of pharyngitis (Pharyngitis Value Set)\nExclude claims/encounters with more than one diagnosis and ED visits that result in an inpatient admission.",
        "step 2": "Determine all pharyngitis Episode Dates. For each member identified in step 1, determine all outpatient or ED claims/encounters with only a diagnosis of pharyngitis.",
        "step 3": "Determine if antibiotics (Table CWP-C) were dispensed for any of the Episode Dates. For each Episode Date with a qualifying diagnosis, determine if antibiotics were dispensed on or up to three days after. Exclude Episode Dates if the member did not receive antibiotics on or three days after the Episode Date.",
        "step 4": "Test for Negative Medication History. Exclude Episode Dates where a new or refill prescription for an antibiotic medication (Table CWP-C) was filled 30 days prior to the Episode Date or where a prescription filled more than 30 days prior to the Episode Date was active on the Episode Date.",
        "step 5": "Calculate continuous enrollment. The member must be continuously enrolled without a gap in coverage from 30 days prior to the Episode Date through 3 days after the Episode Date.",
        "step 6": "Select the IESD. This measure examines the earliest eligible episode per member."
    },
    "Asthma Medication Ratio (AMR) - Administrative Specification": {
        "step 1": "For each member, count the units of controller medications (Table AMR-A) dispensed during the measurement year. Refer to the definition of Units of medications.",
        "step 2": "For each member, count the units of reliever medications (Table AMR-A) dispensed during the measurement year. Refer to the definition of Units of medications.",
        "step 3": "For each member, sum the units calculated in step 1 and step 2 to determine units of total asthma medications.",
        "step 4": "For each member, calculate the ratio of controller medications to total asthma medications using the following formula.\nUnits of Controller Medications (step 1)\nUnits of Total Asthma Medications (step 3)",
        "step 5": "Sum the total number of members who have a ratio of 0.50 or greater in step 4."
    },
    "Asthma Medication Ratio (AMR) - Eligible Population": {
        "step 1": "Identify members as having persistent asthma who met at least one of the following criteria during both the measurement year and the year prior to the measurement year. Criteria need not be the same across both years.\n\u2022\tAt least one ED visit (ED Value Set), with a principal diagnosis of asthma (Asthma Value Set).\n\u2022\tAt least one acute inpatient encounter (Acute Inpatient Value Set), with a principal diagnosis of asthma (Asthma Value Set).\n\u2022\tAt least four outpatient visits (Outpatient Value Set) or observation visits (Observation Value Set), on different dates of service, with any diagnosis of asthma (Asthma Value Set) and at least two asthma medication dispensing events (Table ASM-C). Visit type need not be the same for the four visits.\n\u2022\tAt least four asthma medication dispensing events (Table ASM-C).",
        "step 2": "A member identified as having persistent asthma because of at least four asthma medication dispensing events, where leukotriene modifiers were the sole asthma medication dispensed in that year, must also have at least one diagnosis of asthma (Asthma Value Set), in any setting, in the same year as the leukotriene modifier (i.e., the measurement year or the year prior to the measurement year).",
        "step 3": "Required exclusions\tExclude members who met any of the following criteria:\n\u2022\tMembers who had any diagnosis from any of the following value sets, any time during the member\u2019s history through December 31 of the measurement year:\n\u2013\tEmphysema Value Set.\n\u2013\tOther Emphysema Value Set.\n\u2013\tCOPD Value Set.\n\u2013\tObstructive Chronic Bronchitis Value Set.\n\u2013\tChronic Respiratory Conditions Due to Fumes/Vapors Value Set.\n\u2013\tCystic Fibrosis Value Set.\n\u2013\tAcute Respiratory Failure Value Set.\n\u2022\tMembers who had no asthma medications (controller or reliever) dispensed (Table AMR-A) during the measurement year."
    },
    "Avoidance of Antibiotic Treatment in Adults With Acute Bronchitis (AAB) - Eligible Population": {
        "step 1": "Identify all members in the specified age range who had an outpatient visit (Outpatient Value Set), an observation visit (Observation Value Set) or an ED visit (ED Value Set) during the Intake Period, with a diagnosis of acute bronchitis (Acute Bronchitis Value Set).\nDo not include ED visits that result in an inpatient admission.",
        "step 2": "Determine all acute bronchitis Episode Dates. For each member identified in\nstep 1, determine all outpatient or ED claims/encounters with a diagnosis of acute bronchitis.",
        "step 3": "Test for Negative Comorbid Condition History. Exclude Episode Dates when the member had a claim/encounter with any diagnosis for a comorbid condition during the 12 months prior to or on the Episode Date. A code from any of the following meets criteria for a comorbid condition:\n\u2022\tHIV Value Set.\n\u2022\tMalignant Neoplasms Value Set.\n\u2022\tEmphysema Value Set.\n\u2022\tCOPD Value Set.\n\u2022\tCystic Fibrosis Value Set.\n\u2022\tComorbid Conditions Value Set.",
        "step 4": "Test for Negative Medication History. Exclude Episode Dates where a new or refill prescription for an antibiotic medication (Table AAB-D) was filled 30 days prior to the Episode Date or was active on the Episode Date.",
        "step 5": "Test for Negative Competing Diagnosis. Exclude Episode Dates where during the period 30 days prior to the Episode Date through 7 days after the Episode Date (inclusive) the member had a claim/encounter with any competing diagnosis. A code from either of the following meets criteria for a competing diagnosis:\n\u2022\tPharyngitis Value Set.\n\u2022\tCompeting Diagnosis Value Set.",
        "step 6": "Calculate continuous enrollment. The member must be continuously enrolled with no more than one gap in coverage from 365 days (1 year) prior to the Episode Date through 7 days after the Episode Date.",
        "step 7": "Select the IESD. This measure examines the earliest eligible episode per member."
    },
    "Cardiovascular Monitoring for People With Cardiovascular Disease and Schizophrenia (SMC) - Eligible Population": {
        "step 1": "Identify members with schizophrenia as those who met at least one of the following criteria during the measurement year:\n\u2022\tAt least one acute inpatient encounter with any diagnosis of schizophrenia. Either of the following code combinations meets criteria:\n\u2013\tBH Stand Alone Acute Inpatient Value Set with Schizophrenia Value Set.\n\u2013\tBH Acute Inpatient Value Set with BH Acute Inpatient POS Value Set and Schizophrenia Value Set.\n\u2022\tAt least two visits in an outpatient, intensive outpatient, partial hospitalization, ED or nonacute inpatient setting, on different dates of service, with any diagnosis of schizophrenia. Any two of the following code combinations meet criteria:\n\u2013\tBH Stand Alone Outpatient/PH/IOP Value Set with Schizophrenia Value Set.\n\u2013\tBH Outpatient/PH/IOP Value Set with BH Outpatient/PH/IOP POS Value Set and Schizophrenia Value Set.\n\u2013\tED Value Set with Schizophrenia Value Set.\n\u2013\tBH ED Value Set with BH ED POS Value Set and Schizophrenia Value Set.\n\u2013\tBH Stand Alone Nonacute Inpatient Value Set with Schizophrenia Value Set.\n\u2013\tBH Nonacute Inpatient Value Set with BH Nonacute Inpatient POS Value Set and Schizophrenia Value Set.",
        "step 2": "Identify members from step 1 who also have cardiovascular disease. Members are identified as having cardiovascular disease in two ways: by event or by diagnosis. The organization must use both methods to identify the eligible population, but a member need only be identified by one to be included in the measure.\nEvent. Any of the following during the year prior to the measurement year meet criteria:\n\u2022\tAMI. Discharged from an inpatient setting with an AMI (AMI Value Set). Use both facility and professional claims to identify AMI.\n\u2022\tCABG. Discharged from an inpatient setting with a CABG (CABG Value Set). Use both facility and professional claims to identify CABG.\n\u2022\tPCI. Members who had PCI (PCI Value Set) in any setting (e.g., inpatient, outpatient, ED).\nDiagnosis. Identify members with IVD as those who met at least either of the following criteria during both the measurement year and the year prior to the measurement year. Criteria need not be the same across both years.\n\u2022\tAt least one outpatient visit (Outpatient Value Set) with a diagnosis of IVD (IVD Value Set).\n\u2022\tAt least one acute inpatient encounter (Acute Inpatient Value Set) with a diagnosis of IVD (IVD Value Set)."
    },
    "Comprehensive Diabetes Care (CDC) - To determine if BP is adequately controlled": {
        "step 1": "Identify the most recent BP reading noted during the measurement year. Do not include BP readings that meet the following criteria:\n\u2022\tTaken during an acute inpatient stay or an ED visit.\n\u2022\tTaken during an outpatient visit which was for the sole purpose of having a diagnostic test or surgical procedure performed (e.g., sigmoidoscopy, removal of a mole).\n\u2022\tObtained the same day as a major diagnostic or surgical procedure (e.g., stress test, administration of IV contrast for a radiology procedure, endoscopy).\n\u2022\tReported by or taken by the member.",
        "step 2": "Identify the lowest systolic and lowest diastolic BP reading from the most recent BP notation in the medical record. If there are multiple BPs recorded for a single date, use the lowest systolic and lowest diastolic BP on that date as the representative BP. The systolic and diastolic results do not need to be from the same reading when multiple readings are recorded for a single date.\nThe member is not numerator compliant if the BP does not meet the specified threshold or is missing, or if there is no BP reading during the measurement year or if the reading is incomplete (i.e., the systolic or diastolic level is missing)."
    },
    "Controlling High Blood Pressure (CBP) - determine representative BP": {
        "step 1": "Identify the most recent BP reading noted during the measurement year. The reading must occur after the date when the diagnosis of hypertension was confirmed.\nDo not include BP readings:\n\u2022\tTaken during an acute inpatient stay or an ED visit.\n\u2022\tTaken during an outpatient visit which was for the sole purpose of having a diagnostic test or surgical procedure performed (e.g., sigmoidoscopy, removal of a mole).\n\u2022\tObtained the same day as a major diagnostic or surgical procedure (e.g., stress test, administration of IV contrast for a radiology procedure, endoscopy).\n\u2022\tReported by or taken by the member.\nIf multiple readings were recorded for a single date, use the lowest systolic and lowest diastolic BP on that date as the representative BP. The systolic and diastolic results do not need to be from the same reading.",
        "step 2": "Determine numerator compliance based on the following criteria:\n\u2022\tMembers 18-59 years of age as of December 31 of the measurement year whose BP was <140/90 mm Hg.\n\u2022\tMembers 60-85 years of age as of December 31 of the measurement year and flagged with a diagnosis of diabetes whose BP was <140/90 mm Hg.\n\u2022\tMembers 60-85 years of age as of December 31 of the measurement year and flagged as not having a diagnosis of diabetes whose BP was <150/90 mm Hg.\nThe member is not compliant if the BP reading does not meet the specified threshold or is missing, or if there is no BP reading during the measurement year or if the reading is incomplete (e.g., the systolic or diastolic level is missing).",
        "step 3": "",
        "step 4": ""
    },
    "Controlling High Blood Pressure (CBP) - find the appropriate medical record to review": {
        "step 1": "If the member had more than one PCP for the time period, identify the PCP who most recently provided care to the member.\nIf the member did not visit a PCP for the time period or does not have a PCP, identify the practitioner who most recently provided care to the member.\nIf a practitioner other than the member\u2019s PCP manages the hypertension, the organization may use the medical record of that practitioner.",
        "step 2": "If a member sees one PCP during the denominator confirmation period (on or before June 30 of the measurement year) and another PCP after June 30, the diagnosis of hypertension and the BP reading may be identified through two different medical records.\nIf a member has the same PCP for the entire measurement year, but it is clear from claims or medical record data that a specialist (e.g., cardiologist) manages the member\u2019s hypertension after June 30, the organization may use the PCP\u2019s chart to confirm the diagnosis and use the specialist\u2019s chart to obtain the BP reading. For example, if all recent claims coded with 401 came from the specialist, the organization may use this chart for the most recent BP reading. If the member did not have any visit with the specialist prior to June 30 of the measurement year, the organization must go to another medical record to confirm the diagnosis."
    },
    "Diabetes Monitoring for People With Diabetes and Schizophrenia (SMD) - Eligible Population": {
        "step 1": "Identify members with schizophrenia as those who met at least one of the following criteria during the measurement year:\n\u2022\tAt least one acute inpatient encounter, with any diagnosis of schizophrenia. Either of the following code combinations meet criteria:\n\u2013\tBH Stand Alone Acute Inpatient Value Set with Schizophrenia Value Set.\n\u2013\tBH Acute Inpatient Value Set with BH Acute Inpatient POS Value Set and Schizophrenia Value Set.\n\u2022\tAt least two visits in an outpatient, intensive outpatient, partial hospitalization, ED or nonacute inpatient setting, on different dates of service, with any diagnosis of schizophrenia. Any two of the following code combinations meet criteria:\n\u2013\tBH Stand Alone Outpatient/PH/IOP Value Set with Schizophrenia Value Set.\n\u2013\tBH Outpatient/PH/IOP Value Set with BH Outpatient/PH/IOP POS Value Set and Schizophrenia Value Set.\n\u2013\tED Value Set with Schizophrenia Value Set.",
        "step 2": "Identify members from step 1 who also have diabetes. There are two ways to identify members with diabetes: by claim/encounter data and by pharmacy data. The organization must use both methods to identify the eligible population, but a member need only be identified by one to be included in the measure. Members may be identified as having diabetes during the measurement year or the year prior to the measurement year.\nClaim/encounter data. Members who met any of the following criteria during the measurement year or the year prior to the measurement year (count services that occur over both years):\n\u2022\tAt least two outpatient visits (Outpatient Value Set), observation visits (Observation Value Set), ED visits (ED Value Set) or nonacute inpatient encounters (Nonacute Inpatient Value Set), on different dates of service, with a diagnosis of diabetes (Diabetes Value Set). Visit type need not be the same for the two encounters.\n\u2022\tAt least one acute inpatient encounter (Acute Inpatient Value Set), with a diagnosis of diabetes (Diabetes Value Set).\nPharmacy data. Members who were dispensed insulin or oral hypoglycemics/ antihyperglycemics on an ambulatory basis during the measurement year or year prior to the measurement year (Table CDC-A)."
    },
    "Diabetes Screening for People With Schizophrenia or Bipolar Disorder Who Are Using Antipsychotic Medications (SSD) - Eligible Population": {
        "step 1": "Identify members with schizophrenia or bipolar disorder as those who met at least one of the following criteria during the measurement year.\n\u2022\tAt least one acute inpatient encounter, with any diagnosis of schizophrenia or bipolar disorder. Any of the following code combinations meet criteria:\n\u2013\tBH Stand Alone Acute Inpatient Value Set with Schizophrenia Value Set.\n\u2013\tBH Stand Alone Acute Inpatient Value Set with Bipolar Disorder Value Set.\n\u2013\tBH Acute Inpatient Value Set with BH Acute Inpatient POS Value Set and Schizophrenia Value Set.\n\u2013\tBH Acute Inpatient Value Set with BH Acute Inpatient POS Value Set and Bipolar Disorder Value Set.\n\u2022\tAt least two visits in an outpatient, intensive outpatient, partial hospitalization, ED or nonacute inpatient setting, on different dates of service, with any diagnosis of schizophrenia. Any two of the following code combinations meet criteria:\n\u2013\tBH Stand Alone Outpatient/PH/IOP Value Set with Schizophrenia Value Set.\n\u2013\tBH Outpatient/PH/IOP Value Set with BH Outpatient/PH/IOP POS Value Set and Schizophrenia Value Set.\n\u2013\tED Value Set with Schizophrenia Value Set.\n\u2013\tBH ED Value Set with BH ED POS Value Set and Schizophrenia Value Set.\n\u2013\tBH Stand Alone Nonacute Inpatient Value Set with Schizophrenia Value Set.\n\u2013\tBH Nonacute Inpatient Value Set with BH Nonacute Inpatient POS Value Set and Schizophrenia Value Set.\n\u2022\tAt least two visits in an outpatient, intensive outpatient, partial hospitalization, ED or nonacute inpatient setting, on different dates of service, with any diagnosis of bipolar disorder. Any two of the following code combinations meet criteria:\n\u2013\tBH Stand Alone Outpatient/PH/IOP Value Set with Bipolar Disorder Value Set.\n\u2013\tBH Outpatient/PH/IOP Value Set with BH Outpatient/PH/IOP POS Value Set and Bipolar Disorder Value Set.\n\u2013\tED Value Set with Bipolar Disorder Value Set.\n\u2013\tBH ED Value Set with BH ED POS Value Set and Bipolar Disorder Value Set.\n\u2013\tBH Stand Alone Nonacute Inpatient Value Set with Bipolar Disorder Value Set.\n\u2013\tBH Nonacute Inpatient Value Set with BH Nonacute Inpatient POS Value Set and Bipolar Disorder Value Set.",
        "step 2": "Required exclusions\tExclude members who met any of the following criteria:\n\u2022\tMembers with diabetes. There are two ways to identify members with diabetes: by claim/encounter data and by pharmacy data. The organization must use both methods to identify members with diabetes, but a member need only be identified by one method to be excluded from the measure. Members may be identified as having diabetes during the measurement year or the year prior to the measurement year.\n\u2013\tClaim/encounter data. Members who met at any of the following criteria during the measurement year or the year prior to the measurement year (count services that occur over both years).\n\u2022\tAt least two outpatient visits (Outpatient Value Set), observation visits (Observation Value Set) or nonacute inpatient encounters (Nonacute Inpatient Value Set) on different dates of service, with a diagnosis of diabetes (Diabetes Value Set). Visit type need not be the same for the two encounters.\n\u2022\tAt least one acute inpatient encounter (Acute Inpatient Value Set) with a diagnosis of diabetes (Diabetes Value Set).\n\u2022\tAt least one ED encounter (ED Value Set) with a diagnosis of diabetes (Diabetes Value Set).\n\u2013\tPharmacy data. Members who were dispensed insulin or oral hypoglycemics/ antihyperglycemics during the measurement year or year prior to the measurement year on an ambulatory basis (Table CDC-A).\n\u2022\tMembers who had no antipsychotic medications dispensed during the measurement year. There are two ways to identify dispensing events: by claim/encounter data and by pharmacy data. The organization must use both methods to identify dispensing events, but an event need only be identified by one method to be counted.\n\u2013\tClaim/encounter data. An antipsychotic medication (Long-Acting Injections Value Set).\n\u2013\tPharmacy data. Dispensed an antipsychotic medication (Table SSD-D) on an ambulatory basis."
    },
    "Follow-Up Care for Children Prescribed ADHD Medication (ADD) - Eligible Population - Rate 1 - Initiation Phase": {
        "step 1": "Identify all children in the specified age range who were dispensed an ADHD medication (Table ADD-A) during the 12-month Intake Period.",
        "step 2": "Test for Negative Medication History. For each member identified in step 1, test each ADHD prescription for a Negative Medication History. The IPSD is the dispensing date of the earliest ADHD prescription in the Intake Period with a Negative Medication History.",
        "step 3": "Calculate continuous enrollment. Members must be continuously enrolled for 120 days (4 months) prior to the IPSD through 30 days after the IPSD.",
        "step 4": "Exclude members who had an acute inpatient encounter for mental health or chemical dependency during the 30 days after the IPSD. An acute inpatient encounter in combination with any of the following meet criteria:\n- A principal mental health diagnosis (Mental Health Diagnosis Value Set).\n- A principal diagnosis of chemical dependency (Chemical Dependency Value Set).\n"
    },
    "Frequency of Ongoing Prenatal Care (FPC) - Administrative Specification": {
        "step 1": "Identify the delivery date using hospital discharge data.",
        "step 2": "Identify the date when the member enrolled in the organization and determine the stage of pregnancy at time of enrollment. If the member has gaps in enrollment during pregnancy, use the last enrollment segment to determine continuous enrollment in the organization. For members with a gap in enrollment any time during pregnancy (including a gap in the first trimester), the last enrollment segment is the enrollment start date during the pregnancy that is closest to the delivery date.\nUse the following approach (or an equivalent method) to calculate the stage of pregnancy at time of enrollment. If gestational age is not available, assume a gestational age of 280 days (40 weeks).\n\u2022\tConvert gestational age into days.\n\u2022\tSubtract gestational age (in days) from the date of delivery (step 1).\n\u2022\tSubtract the date obtained above from the date when the member enrolled in the organization to determine the stage of pregnancy at time of enrollment.\n\u2022\tDivide the numbers of days the member was pregnant at enrollment (step 3) by 30. Round the resulting number according to the .5 rule to a whole number.\nFor example, delivery date is August 8, 2014; gestational age is 33 weeks; date of enrollment is May 6, 2014. Given these variables, the process is:\n\u2013\tGestational age in days is 231 days (33 weeks \uf0b4 7 days/week).\n\u2013\tDate of delivery \u2013 gestational age (in days) is December 20, 2013 (August 8, 2014 \u2013 231 days).\n\u2013\tDate when the member enrolled in the organization \u2013 date obtained in step 2 is 137 days (May 6, 2014 \u2013 December 20, 2013).\n\u2013\tMonth in which prenatal care began is 4.56 months (137 days/30 days) and then round up to 5 months using the 0.5 rule.\nThis member\u2019s stage of pregnancy at time of enrollment is 5 months.",
        "step 3": "Use Table FPC-A to find the number of recommended prenatal visits by gestational age and stage of pregnancy at time of enrollment per the American College of Obstetricians and Gynecologists (ACOG). The chart subtracts the number of missed visits prior to the date the member enrolled from the number of recommended visits for a given gestational age.\nACOG recommends that women with an uncomplicated pregnancy receive visits every\n4 weeks for the first 28 weeks of pregnancy, every 2\u20133 weeks until 36 weeks of pregnancy, and weekly thereafter. For example, ACOG recommends 14 visits for a 40-week pregnancy. If the member enrolled during her fourth month (3 missed visits prior to enrollment in the organization), the expected number of visits is 14 \u2013 3 = 11.\nFor deliveries with a gestational age <28 weeks or >43 weeks, calculate the expected number of prenatal care visits using the date when the member enrolled and ACOG\u2019s recommended schedule of visits. For example, if gestational age is 26 weeks and the member enrolled during her second month of pregnancy, the expected number of prenatal care visits is 5 (6 expected visits [1 visit every 4 weeks or 6 visits in 24 weeks], less 1 visit missed in the first month).\nIf gestational age is 44 weeks and the member enrolled during her third month of pregnancy, the expected number of prenatal care visits is 16 (14 expected visits for a 40-week gestation plus 1 visit each additional week [18 total expected prenatal care visits], less 2 visits missed in the first and second months).",
        "step 4": "Identify the number of discrete prenatal care visits the member received during the course of her pregnancy and while enrolled in the organization using claims and encounter data.\nTo identify prenatal visits that occurred during the first trimester, refer to the Prenatal and Postpartum Care measure decisions rules for Identifying Prenatal Care For Women Continuously Enrolled During the First Trimester.\nTo identify prenatal visits that occurred during the second and third trimester, refer to the prenatal and postpartum care measure instructions for Identifying Prenatal Care For Women Not Continuously Enrolled During the First Trimester. Visits that occur on the date of delivery and meet the prenatal visit criteria count toward the measure.\nAll criteria must be met for encounters to be counted as a discrete prenatal care visit. For example, Decision Rules 2 and 3 require multiple components (typically a visit combined with a diagnosis code or another prenatal service such as a lab test or an ultrasound). Ultrasound and lab results alone are not considered a discrete prenatal care visit unless they are combined with other criteria.\nServices that occur over multiple visits can be combined to create a discrete prenatal care visit if all services occur within the time frame established in the measure and services are not double counted. Organizations must develop systems to avoid double counting. For example, a code from the Stand Alone Prenatal Visits Value Set on the same date of service as a code from the Prenatal Visits Value Set is interpreted to represent a single visit/encounter and may not be counted twice. If the member had a gap in enrollment, count only the visits received during the last enrollment segment.",
        "step 5": "Calculate the ratio of observed visits (step 4) to expected visits (step 3).",
        "step 6": "Report each woman in the appropriate category:\n\u2022\t<21 percent.\n\u2022\t21 percent\u201340 percent.\n\u2022\t41 percent\u201360 percent.\t\u2022\t61 percent\u201380 percent.\n\u2022\t\u226581 percent of expected visits."
    },
    "Frequency of Ongoing Prenatal Care (FPC) - Eligible Population": {
        "step 1": "Identify deliveries. Identify all women with a delivery between November 6 of the year prior to the measurement year and November 5 of the measurement year. Either of the following meets criteria:\n\u2022\tA delivery (Deliveries Value Set).\n\u2022\tA delivery on an infant claim (Deliveries Infant Record Value Set), where the organization can link infant and mother records.",
        "step 2": "Exclude non-live births (Non-live Births Value Set).",
        "step 3": "Identify continuous enrollment. Determine if enrollment was continuous between 43 days prior to delivery and 56 days after delivery, with no gaps."
    },
    "Guidelines for Relative Resource Use Measures - Calculating Standard Cost": {
        "step 1": "Identify eligible members for each major clinical condition and assign them a risk group.",
        "step 2": "Identify all services rendered during the treatment period for each service category:\n\u2022\tInpatient Facility (services provided by a facility during an inpatient stay).\n\u2022\tE&M (inpatient visits, and outpatient visits including office visits, consultations and other services).\n\u2022\tSurgery and Procedure (inpatient and outpatient procedures).\n\u2022\tDiagnostic Imaging.\n\u2022\tDiagnostic Laboratory.\n\u2022\tPharmacy (ambulatory prescriptions).",
        "step 3": "Multiply the standard price by the units of service to compute a standard cost for the service. Refer to each service category\u2019s instructions (i.e., Calculating Total Standard Cost).",
        "step 4": "For each major clinical condition, sum each member\u2019s total standard cost for each service category.",
        "step 5": "Report the total standard cost by age, gender and risk group.",
        "step 6": "In each service category, if a member\u2019s standard cost exceeds the cap amount, report the total standard cost, including only the cap amount from Table SPT-CAP. Do not exclude members who exceed the cap."
    },
    "Guidelines for Relative Resource Use Measures - Calculating Total Standard Cost and Frequency_Inpatient Facility": {
        "step 1": "Identify all inpatient stays that occurred during the treatment period. Include stays that started before the treatment period or ended after the close of the treatment period. Create a unique record describing the member\u2019s inpatient stay.",
        "step 2": "Determine the LOS for frequency reporting. Compute the LOS in days, using paid for or expected-to-be-paid-for days only. Include all paid days in the calculation, whether or not they fall inside the treatment period. Use this LOS when reporting the frequency counts for each inpatient stay.",
        "step 3": "Determine the LOS category for standard cost reporting. Assign the appropriate LOS group using Table C.\nTable C: Length of Stay Group\nLOS (Days)\tLOS GRP\n1\t\tA\n2\t\tB\n3-4\t\tC\n5-6 \tD\n7-8 \tE\n9-15 \tF\n16 or more\tG",
        "step 4": "Determine the LOS per diem multiplier. If the inpatient stay falls within the treatment period,\nuse the total days the organization paid for or expects to pay for as the per diem multiplier. If the inpatient stay does not fall inside the treatment period, or if the organization did not pay for all days or does not expect to pay for all days, count only the days within the treatment period (including the last day of the treatment period) that are paid for or expected to be paid for, as the per diem multiplier.",
        "step 5": "Determine if the inpatient stay is acute or nonacute. Nonacute stays include nursing home, skilled nursing facility, rehabilitation, hospice, hospital transitional care, swing bed and respite; all other inpatient stays are acute.\nReport acute and nonacute stays separately when reporting frequency of inpatient stays.\nNote: SPT-INP tables assign the acute field a value of \u201c1\u201d if the discharge was from an acute inpatient stay and a value of \u201c0\u201d if the discharge is from a nonacute stay.",
        "step 6": "Assign an Aggregate Diagnostic Service Category (ADSC) for the inpatient stay using the principal discharge diagnosis. To assign ADSC, download the ADSC Table from the NCQA Web site (www.ncqa.org) and match the principal ICD-9-CM Diagnosis code from the discharge claim to an ADSC. If the principal ICD-9-CM Diagnosis code is invalid or missing, or cannot be determined, map the inpatient stay to the ADSC Table\u2019s MISA category.",
        "step 7": "Determine if the member underwent major surgery during the inpatient stay. Identify major surgeries by using the list of codes from the Maj-Surg Table. Flag members if one procedure code in the Maj-Surg Table is present from any provider during the stay.\nIf the inpatient stay is acute and has a major surgery, include it in the Acute Surgery category for frequency reporting. If the stay is acute but does not have a major surgery, include it in the Acute Medicine category. Nonacute stays are not categorized as surgical or nonsurgical for frequency reporting.\nNote: SPT-INP-ADSC assigns the field MAJSURG a value of \u201c1\u201d to indicate the standard price when a major surgery is identified and a value of \u201c0\u201d if no major surgery is identified during the member\u2019s inpatient stay.",
        "step 8": "Match each ADSC, LOS group, major surgery flag and acute or nonacute assignment for the stay to the NCQA-provided SPT to obtain the assigned standard price. Multiply the per diem multiplier by the per diem standard price to compute the total standard cost for the stay.\nFor frequency reporting, report the stay in the appropriate category based on the acute or nonacute assignment and surgery or medicine assignment."
    },
    "Guidelines for Relative Resource Use Measures - Calculating Total Standard Cost and Frequency_Pharmacy Services": {
        "step 1": "Identify all ambulatory prescriptions dispensed (pharmacy services) during the treatment period.",
        "step 2": "Identify the NDC code and the metric quantity for each prescription. If metric quantity is available, the organization must use it to determine standard price. If the metric quantity is not available, use the standard unit price per day.\nOrganizations that use proprietary or regional codes must map them to standard NDC codes.",
        "step 3": "Download Table SPT-Pharm from the NCQA Web site (www.ncqa.org). The table contains:\n\u2022\tThe NDC code.\n\u2022\tA standard unit price per metric quantity.\n\u2022\tA standard unit price per day.\n\u2022\tPrescription category:\n\u2013\tName brand only (N1).\n\u2013\tName brand\u2014Generic exists (N2).\t\u2013\tGeneric only (G1).\n\u2013\tGeneric name\u2014Name brand exists (G2).",
        "step 4": "Match each NDC code to the appropriate row in Table SPT-Pharm.",
        "step 5": "For pharmacy prescription utilization, aggregate and report service frequencies by organization, in each prescription category, at the total level.\nOne prescription is an amount lasting 30 days or less. To calculate the number of prescriptions when the days supply is 30 days or more, divide the days supply by 30 and round down to convert.",
        "step 6": "If the metric quantity is available, multiply the metric quantity dispensed by the standard price per metric quantity for each prescription.",
        "step 7": "If the metric quantity is unavailable, multiply the days supply dispensed by the standard unit price per day for each prescription.",
        "step 8": "Sum the unit prices for all unique prescription dispensing events."
    },
    "Guidelines for Relative Resource Use Measures - Calculating Total Standard Cost_Diagnostic Imaging Services": {
        "step 1": "Identify all imaging services during the treatment period. The valid procedure and revenue codes for these services are listed in Table SPT-IMAG.",
        "step 2": "Identify codes to price. CPT procedure codes are the preferred codes for pricing imaging services. If a CPT code is present for a service, price the service using the available CPT code and procedure modifier (if applicable) using Table SPT-IMAG. If a CPT code is not present for a service, price the service using the available revenue code.\nIdentify modifier codes when a CPT code is present. Procedure modifiers are sometimes used to define a service in more detail. In Table SPT-IMAG, the standard price for the same CPT code can include multiple rows, reflecting the combinations of CPT codes and modifiers.\nFor imaging services, Table SPT-IMAG recognizes the following applicable modifiers:\n\u2022\t26 = Professional Component.\n\u2022\tTC = Technical Component.\nIf an imaging service is billed with a blank modifier, match the procedure code and blank modifier on the service to the appropriate row in Table SPT-IMAG.\nIf an imaging service is billed with an applicable modifier, match the procedure code and modifier on the service to the appropriate row in Table SPT-IMAG.\nIf an imaging service is billed with a no applicable modifier, set the procedure modifier to blank and match the procedure code and blank modifier on the service to the appropriate row in Table SPT-IMAG.\nIf the procedure code has no modifiers or if all modifiers for a specific procedure code are not applicable, price the procedure code with a blank modifier.\nRefer to the \u201cExample\u201d table in Calculating Total Standard Cost: Surgery and Procedure.\nIf the same service is billed by multiple providers, include and price all services. For example, if a physician and a facility bill for the same service, price both.",
        "step 3": "Download Table SPT-IMAG from the NCQA Web site (www.ncqa.org).",
        "step 4": "Match each applicable procedure or revenue code to obtain the assigned standard price for the service.",
        "step 5": "Multiply the standard price by the number of units associated with the service. Most services have one unit.",
        "step 6": "Sum the standard prices across the imaging services to calculate total cost."
    },
    "Guidelines for Relative Resource Use Measures - Calculating Total Standard Cost_Diagnostic Laboratory Services": {
        "step 1": "Identify all laboratory services during the treatment period. The valid procedure and revenue codes for these services are listed in Table SPT-LAB.",
        "step 2": "Identify codes to price. CPT procedure codes are the preferred codes for pricing laboratory services. If a CPT code is present for a service, price the service using the available CPT code and procedure modifier (if applicable) using Table SPT-LAB. If a CPT code is not present for a service, price the service using the available revenue code.\nIdentify modifier codes when a CPT code is present. Procedure modifiers are sometimes used to define a service in more detail. In Table SPT-LAB, the standard price for the same CPT code can include multiple rows, reflecting the combinations of CPT codes and modifiers.\nFor laboratory services, Table SPT-Lab recognizes the following applicable modifiers:\n\u2022\t26 = Professional Component.\n\u2022\tTC = Technical Component.\nIf a laboratory service is billed with a blank modifier, match the procedure code and blank modifier on the service to the appropriate row in Table SPT-LAB.\nIf a laboratory service is billed with an applicable modifier, match the procedure code and modifier on the service to the appropriate row in Table SPT-LAB.\nIf a laboratory service is billed with a no applicable modifier, set the procedure modifier to blank and match the procedure code and blank modifier on the service to the appropriate row in Table SPT-LAB.\nIf the procedure code has no modifiers or if all modifiers for a specific procedure code are not applicable, price the procedure code with a blank modifier.\nRefer to the \u201cExample\u201d table in Calculating Total Standard Cost: Surgery and Procedure.\nIf the same service is billed by multiple providers, include and price all services. For example, if a physician and a facility bill for the same service, price both.",
        "step 3": "Download Table SPT-LAB from the NCQA Web site (www.ncqa.org).",
        "step 4": "Match each applicable procedure and applicable procedure modifier or revenue code to obtain the assigned standard price for the service.",
        "step 5": "Multiply the standard price by the number of units associated with the service. Most services have one unit.",
        "step 6": "Sum the standard prices across the laboratory services to calculate total cost."
    },
    "Guidelines for Relative Resource Use Measures - Calculating Total Standard Cost_E&M": {
        "step 1": "Identify all E&M services that occurred during the treatment period. The valid E&M codes used to select these services are listed in Table SPT-EM.",
        "step 2": "Match each E&M service to the CPT codes in Table SPT-EM and assign the standard price to the E&M service.",
        "step 3": "Multiply the standard price by the number of units associated with the E&M service. Most services have one unit.",
        "step 4": "Sum the standard prices across the E&M services to calculate the total cost. Include all units of service on a claim line. Sum E&M services labeled as inpatient separate from those labeled as outpatient services."
    },
    "Guidelines for Relative Resource Use Measures - Calculating Total Standard Cost_Surgery and Procedure": {
        "step 1": "Identify all surgery and procedure services provided by physicians and other professional providers during the treatment period. The valid procedure codes for these services are listed in Table SPT-Surg-Proc.",
        "step 2": "Identify modifier codes. Procedure modifiers are sometimes used to define a service in more detail. The standard price for procedure modifiers varies, so these modifiers are combined with the procedure code to match to the appropriate row in the SPT. Use only the applicable modifiers contained in the SPTs. If a specific modifier is not included in the SPT, it is considered a no applicable modifier.\nIf a procedure code is billed with a no applicable modifier, set the modifier to blank. If the procedure code has no modifiers or if there are no applicable modifiers for a specific procedure code, price the procedure code with a blank modifier.\nSurgery and Procedure CPT codes that have a proprietary modifier indicating an anesthesiology bill are not priced.",
        "step 3": "Identify surgeries or procedures provided during an acute or nonacute inpatient stay. In the SPT, services provided in an inpatient setting are under the Excel workbook tab labeled \u201cStd Price\u2014IP Surgery\u201d and services provided in an outpatient setting are under the Excel workbook tab labeled \u201cStd Price\u2014OP Surgery.\u201d Organizations can distinguish between services provided in an inpatient or outpatient setting in several ways:\n\u2022\tTreat a surgery or procedure as outpatient unless it has a POS code of 21, 31, 39, 51\nor 61.\n\u2022\tIf the POS code is not available, determine if the member was admitted overnight for the surgery or procedure. If so, treat the surgery or procedure as inpatient; if not, treat it as outpatient.\n\u2022\tTreat a surgery as inpatient if it falls between the dates of an inpatient stay. If a surgery was used to classify an inpatient stay as surgical, price the surgery as inpatient.",
        "step 4": "Download Table SPT-Surg-Proc for surgery and procedure services from the NCQA Web site (www.ncqa.org).",
        "step 5": "Match each procedure code, applicable modifier and POS to obtain the assigned standard price for the service.",
        "step 6": "Multiply the standard price by the number of units associated with the service. Most services have one unit.",
        "step 7": "Sum the standard prices across the surgery and procedure services to calculate the total cost. Sum inpatient and outpatient costs separately."
    },
    "Guidelines for Relative Resource Use Measures - Calculating member months": {
        "step 1": "For chronic condition measures, determine member months using a prespecified day\n(e.g., the 15th or the last day of the month), which is determined by the organization\u2019s administrative processes. The day selected must be consistent from month to month and year to year. For example, if the organization tallies membership on the 15th of the month and Ms. X is enrolled in the organization on January 15, Ms. X contributes one member month in January.\nRetroactive enrollment. Organizations may count any month in which members were enrolled retrospectively and the organization received a retroactive capitation payment.",
        "step 2": "Use the member\u2019s age on the last day of the treatment period to determine the age group where member months are counted. For example, for Relative Resource Use for People With Diabetes, if Ms. X turns 18 on December 31 and is enrolled for the entire treatment period, she contributes 12 member months to the 18\u201344 age category.",
        "step 3": "Attribute all member months to the product line in which the member is enrolled on the last day of the treatment period."
    },
    "Guidelines for Relative Resource Use Measures - HCC-RRU Risk Adjustment": {
        "step 1": "Identify the qualified service diagnosis.\nUse the following value sets and identify all diagnoses for encounters during the treatment period based on the date of service for outpatient or ED services or on the discharge date for inpatient stays.\n\u2022\tOutpatient (Outpatient Value Set).\n\u2022\tObservation (Observation Value Set).\n\u2022\tAcute inpatient (Acute Inpatient Value Set).\n\u2022\tNonacute inpatient (Nonacute Inpatient Value Set).\n\u2022\tED (ED Value Set).\n\u2022\tSurgery and procedure services. Services with a CPT Procedure code in Table\nHCC\u2014Surg.\nUse all diagnosis codes for all services that meet the criteria listed above to complete the steps below.",
        "step 2": "Assign each diagnosis code to one CC category (CC) using Table CC\u2014Comorbid.\nExclude all diagnoses that cannot be assigned to a CC category. For members with no qualifying diagnoses from face-to-face encounters, skip to step 6.\nAll digits must match exactly when mapping diagnosis codes to the CCs.",
        "step 3": "Determine HCCs for each CC identified. Refer to Table HCC\u2014Rank.\nFor a member\u2019s CC list, match the CC code to the CC code in the table, and assign:\n\u2022\tThe ranking group.\n\u2022\tThe rank.\n\u2022\tThe HCC.\nFor CCs that do not match to Table HCC\u2014Rank, use the CC as the HCC and assign a rank\nof 1.\nNote: One CC can map to multiple HCCs; each HCC can have one or more CCs.",
        "step 4": "Select only the highest-ranked HCC in each ranking group using the Rank column (1 is the highest possible rank).\nDrop all other HCCs in each ranking group and de-duplicate the HCC list if necessary.\nNote: Refer to the Plan All-Cause Readmissions (PCR) measure for a Comorbid CC calculation example.",
        "step 5": "Identify combination HCCs listed in Table HCC\u2014Comb.\nSome combinations suggest a greater amount of risk when observed together. For example, when diabetes and CHF are present, an increased amount of risk is evident. Additional HCCs are selected to account for these relationships.\nCompare each member\u2019s list of unique HCCs to those in the HCC column in Table HCC\u2014Comb and assign any additional HCC conditions.\nFor fully nested combinations (e.g., the diabetes/CHF combination is nested in the diabetes/ CHF/renal combination), use only the more comprehensive pattern. In this example, only the diabetes/CHF/renal combination is counted.\nFor overlapping combinations (e.g., the CHF, COPD combination overlaps the CHR/renal/ diabetes combination), use both sets of combinations. In this example, both CHF/COPD and CHF/renal/diabetes combinations are counted.\nBased on the combinations, a member can have none, one or more of these additional HCCs.\nNote: Refer to the PCR measure for a combination HCC calculation example.",
        "step 6": "Identify demographic HCCs for RRU.\nCategorize members by age and gender using the age ranges described in Table RRU\u2014Age/ Gender\u2014HCC. Assign a demographic HCC based on gender and the member\u2019s age on the last day of the treatment period.\nAt the end of step 6, each member will have a final list of HCCs that includes at least one demographic HCC and none, one or more HCCs based on steps 1\u20135.\nNote: Each RRU measure has its own demographic criteria.",
        "step 7": "Calculate the weight for all the HCCs on each member\u2019s list using Table RRU\u2014Weight. Each HCC for RRU carries a predefined risk weight.",
        "step 8": "Sum each member\u2019s risk weights based on the final list of HCCs. A member\u2019s risk score is the sum of the risk weights for all HCCs on that member\u2019s list. Sum the weights based on the member\u2019s HCC lists. Round the final risk score to four decimal places.",
        "step 9": "Use the table below to assign the member to a risk group based on risk score.\nFor example, a member with a total HCC risk score of 1.2300 is assigned to Risk Group 5. Report all member months and cost information for this member in this risk group, within the appropriate age and gender stratifications."
    },
    "Guidelines for Relative Resource Use Measures - Measurement and Calculation Process": {
        "step 1": "Identify members for each major clinical condition and determine the age and gender category for each member. The medical and pharmacy services for these members are identified for the treatment period.",
        "step 2": "Calculate total standard costs for each service category using NCQA-provided SPTs. Specifications list services to be measured and SPTs provide the standard price. Refer to the SPT Tables posted on the NCQA Web site (www.ncqa.org).",
        "step 3": "Report service frequency and standard costs for the eligible population by member cohort, across all service categories.",
        "step 4": "NCQA uses the stratified data submitted by all organizations to calculate each organization\u2019s expected RRU amounts for each major clinical condition."
    },
    "Guidelines for Relative Resource Use Measures - Steps for Calculating Service Categories": {
        "step 1": "Identify eligible members for each major clinical condition and assign them a risk group.",
        "step 2": "Identify all inpatient, ED, pharmacy and condition-specific services rendered during the treatment period.",
        "step 3": "Match the services to the codes provided in the specifications then group them into the following utilization categories:\n\u2022\tAcute Medicine: Discharges, Days.\n\u2022\tAcute Surgery: Discharges, Days.\n\u2022\tNonacute: Discharges, Days.\n\u2022\tED: Discharges.\n\u2022\tPharmacy Utilization:\n\u2013\tName brand only.\n\u2013\tName brand\u2014Generic exists.\n\u2013\tGeneric only.\n\u2013\tGeneric name\u2014Name brand exists.\n\u2022\tOther condition-specific categories (e.g., MRI, cardiac procedures):\n\u2022\tRCA and RDI report information on select cardiac procedures.",
        "step 4": "Count the unique services rendered during the treatment period in each utilization category, for each risk group. Refer to Guideline 8\u2014Counting multiple billings for the same date of service.\nCount the pharmacy prescriptions dispensed during the treatment period in each utilization category. One prescription is an amount lasting 30 days or less. To calculate the number of prescriptions that have a days supply of 30 days or longer, divide the days supply by 30 and round down to convert.",
        "step 5": "Aggregate and report service frequencies by age, gender and risk group."
    },
    "Initiation and Engagement of Alcohol and Other Drug Dependence Treatment (IET) - Eligible Population": {
        "step 1": "Identify the Index Episode. Identify all members in the specified age range who during the Intake Period had one of the following:\n\u2022\tAn outpatient visit, intensive outpatient visit or partial hospitalization with a diagnosis of AOD. Any of the following code combinations meet criteria:\n\u2013\tIET Stand Alone Visits Value Set with AOD Dependence Value Set.\n\u2013\tIET Visits Group 1 Value Set with IET POS Group 1 Value Set and AOD Dependence Value Set.\n\u2013\tIET Visits Group 2 Value Set with IET POS Group 2 Value Set and AOD Dependence Value Set.\n\u2022\tA detoxification visit (Detoxification Value Set).\n\u2022\tAn ED visit (ED Value Set) with a diagnosis of AOD (AOD Dependence Value Set).\n\u2022\tAn inpatient discharge with a diagnosis of AOD as identified by either of the following:\n\u2013\tAn inpatient discharge with a diagnosis of AOD (AOD Dependence Value Set).\n\u2013\tAn inpatient discharge with an AOD procedure code (AOD Procedures Value Set).\nFor members with more than one episode of AOD, use the first episode.\nFor members whose first episode was an ED visit that resulted in an inpatient event, use the inpatient discharge.\nSelect the IESD.",
        "step 2": "Test for Negative Diagnosis History. Exclude members who had a claim/encounter with a diagnosis of AOD (AOD Dependence Value Set) during the 60 days (2 months) before the IESD.\nFor an inpatient IESD, use the admission date to determine the Negative Diagnosis History.\nFor an ED visit that results in an inpatient event, use the ED date of service to determine the Negative Diagnosis History.",
        "step 3": "Calculate continuous enrollment. Members must be continuously enrolled for 60 days\n(2 months) before the IESD through 44 days after the IESD, with no gaps."
    },
    "Medication Management for People With Asthma (MMA) - Administrative Specification": {
        "step 1": "Identify the IPSD. The IPSD is the earliest dispensing event for any asthma controller medication (Table ASM-D) during the measurement year.",
        "step 2": "To determine the treatment period, calculate the number of days from the IPSD (inclusive) to the end of the measurement year.",
        "step 3": "Count the days covered by at least one prescription for an asthma controller medication (Table ASM-D) during the treatment period. To ensure that days supply that extends beyond the measurement year is not counted, subtract any days supply that extends beyond December 31 of the measurement year.",
        "step 4": "Calculate the member\u2019s PDC using the following equation. Round (using the .5 rule) to two decimal places.\nTotal Days Covered by a Controller Medication in the Treatment Period (step 3)\nTotal Days in Treatment Period (step 2)"
    },
    "Medication Management for People With Asthma (MMA) - Eligible Population": {
        "step 1": "Identify members as having persistent asthma who met at least one of the following criteria during both the measurement year and the year prior to the measurement year. Criteria need not be the same across both years.\n\u2022\tAt least one ED visit (ED Value Set), with a principal diagnosis of asthma (Asthma Value Set).\n\u2022\tAt least one acute inpatient encounter (Acute Inpatient Value Set), with a principal diagnosis of asthma (Asthma Value Set).\n\u2022\tAt least four outpatient visits (Outpatient Value Set) or observation visits (Observation Value Set) on different dates of service, with any diagnosis of asthma (Asthma Value Set) and at least two asthma medication dispensing events (Table ASM-C). Visit type need not be the same for the four visits.\n\u2022\tAt least four asthma medication dispensing events (Table ASM-C).",
        "step 2": "A member identified as having persistent asthma because of at least four asthma medication dispensing events, where leukotriene modifiers were the sole asthma medication dispensed in that year, must also have at least one diagnosis of asthma (Asthma Value Set), in any setting, in the same year as the leukotriene modifier (i.e., measurement year or year prior to the measurement year).",
        "step 3": "Required exclusions\tExclude members who met any of the following criteria:\n\u2022\tMembers who had any diagnosis from any of the following value sets, any time during the member\u2019s history through December 31 of the measurement year:\n\u2013\tEmphysema Value Set.\n\u2013\tOther Emphysema Value Set.\n\u2013\tCOPD Value Set.\n\u2013\tObstructive Chronic Bronchitis Value Set.\n\u2013\tChronic Respiratory Conditions Due to Fumes/Vapors Value Set.\n\u2013\tCystic Fibrosis Value Set.\n\u2013\tAcute Respiratory Failure Value Set.\n\u2022\tMembers who had no asthma controller medications (Table ASM-D) dispensed during the measurement year."
    },
    "Osteoporosis Management in Women Who Had a Fracture (OMW) - Eligible Population": {
        "step 1": "Identify all members who had an outpatient visit (Outpatient Value Set), an observation visit (Observation Value Set), an ED visit (ED Value Set), a nonacute inpatient encounter (Nonacute Inpatient Value Set) or an acute inpatient encounter (Acute Inpatient Value Set) for a fracture (Fractures Value Set) during the Intake Period. If the member had more than one fracture, include only the first fracture.",
        "step 2": "Test for Negative Diagnosis History. Exclude members with an outpatient visit (Outpatient Value Set), an observation visit (Observation Value Set), an ED visit (ED Value Set), a nonacute inpatient encounter (Nonacute Inpatient Value Set) or an acute inpatient encounter (Acute Inpatient Value Set) for a fracture (Fractures Value Set) during the 60 days (2 months) prior to the IESD.\nFor fractures requiring an inpatient stay, use the admission date to determine Negative Diagnosis History.\nFor direct transfers, use the first admission to determine the Negative Diagnosis History.",
        "step 3": "Calculate continuous enrollment. Members must be continuously enrolled during the 12 months prior to the fracture through 180 days (6 months) post-fracture.",
        "step 4": "Required exclusions\tExclude members who met any of the following criteria:\n\u2022\tMembers who had a BMD test (Bone Mineral Density Tests Value Set) during the 730 days (24 months) prior to the IESD.\n\u2022\tMembers who had a claim/encounter for osteoporosis therapy (Osteoporosis Medications Value Set) during the 365 days (12 months) prior to the IESD.\n\u2022\tMembers who received a dispensed prescription or had an active prescription to treat osteoporosis (Table OMW-C) during the 365 days (12 months) prior to the IESD.\nFor an inpatient encounter, use the admission date to determine the days  prior to the IESD."
    },
    "Pharmacotherapy Management of COPD Exacerbation (PCE) - Eligible Population": {
        "step 1": "Identify all members who during the Intake Period had an acute inpatient discharge (Acute Inpatient UB Revenue Value Set) or an ED visit (ED Value Set) with a primary diagnosis of COPD (COPD Value Set), emphysema (Emphysema Value Set) or chronic bronchitis (Chronic Bronchitis Value Set).\nDo not include ED visits that result in an inpatient admission.\nNote: The denominator for this measure is based on acute inpatient discharges and ED visits, not on members. Only UB Revenue codes are used to identify acute inpatient discharges because using other codes could result in double-counting.",
        "step 2": "Identify all COPD Episode Dates. For each member identified in step 1, identify all acute inpatient discharges and ED visits. Do not include ED visits that result in an inpatient admission.",
        "step 3": "Test for transfers. Exclude Episode Dates when the member was transferred directly to an acute or nonacute care facility for any diagnosis.",
        "step 4": "Test for readmission and additional ED visits. Exclude Episode Dates when the member was readmitted to an acute or nonacute care facility for any diagnosis within 14 days after the Episode Date. Exclude Episode Dates when the member had an ED visit for any diagnosis within 14 days after the Episode Date.",
        "step 5": "Calculate continuous enrollment. The member must be continuously enrolled without a gap in coverage from the Episode Date through 30 days after the Episode Date.\nNote: All Episode Dates that were not excluded remain in the denominator. The denominator for this measure is based on acute inpatient discharges and ED visits, not members."
    },
    "Plan All-Cause Readmissions (PCR) - Administrative Specification": {
        "step 1": "Identify all acute inpatient stays with a discharge date on or between January 1 and December 1 of the measurement year.\nInclude acute admissions to behavioral healthcare facilities.",
        "step 2": "Acute-to\u2013acute transfers: Keep the original admission date as the Index Admission Date, but use the transfer\u2019s discharge date as the Index Discharge Date.",
        "step 3": "Exclude acute inpatient hospital discharges with a principal diagnosis of pregnancy (Pregnancy Value Set) or a principal diagnosis for a condition originating in the perinatal period (Perinatal Conditions Value Set).",
        "step 4": "Required exclusions\tExclude stays for the following reasons:\n\u2022\tInpatient stays with discharges for death.\n\u2022\tAcute inpatient discharge with a principal diagnosis of pregnancy (Pregnancy Value Set).\n\u2022\tAcute inpatient discharge with a principal diagnosis of a condition originating in the perinatal period (Perinatal Conditions Value Set).",
        "step 5": "Required exclusions\tFor all acute inpatient discharges identified using steps 1\u20134, determine if there was a planned hospital stay within 30 days using all acute inpatient stays. Exclude any acute inpatient discharge as an Index Hospital Stay if the admission date of the first planned hospital stay is within 30 days and includes any of the following.\n\u2022\tA principal diagnosis of maintenance chemotherapy (Chemotherapy Value Set).\n\u2022\tA principal diagnosis of rehabilitation (Rehabilitation Value Set).\n\u2022\tAn organ transplant (Kidney Transplant Value Set, Bone Marrow Transplant Value Set, Organ Transplant Other Than Kidney Value Set).\n\u2022\tA potentially planned procedure (Potentially Planned Procedure Value Set) without a principal acute diagnosis (Acute Condition Value Set)."
    },
    "Plan All-Cause Readmissions (PCR) - Risk Adjustment Determination": {
        "step 1": "Identify all diagnoses for encounters during the classification period. Include the following when identifying encounters:\n\u2022\tOutpatient visits (Outpatient Value Set).\n\u2022\tObservation visits (Observation Value Set).\n\u2022\tNonacute inpatient encounters (Nonacute Inpatient Value Set).\n\u2022\tAcute inpatient encounters (Acute Inpatient Value Set).\n\u2022\tED visits (ED Value Set).\nExclude the primary discharge diagnosis on the IHS.",
        "step 2": "Assign each diagnosis to one comorbid Clinical Condition (CC) category using Table CC\u2014Comorbid.\nExclude all diagnoses that cannot be assigned to a comorbid CC category. For members with no qualifying diagnoses from face-to-face encounters, skip to the Risk Adjustment Weighting section.\nAll digits must match exactly when mapping diagnosis codes to the comorbid CCs.",
        "step 3": "Determine HCCs for each comorbid CC identified. Refer to Table HCC\u2014Rank.\nFor each stay\u2019s comorbid CC list, match the comorbid CC code to the comorbid CC code in the table, and assign:\n\u2022\tThe ranking group.\n\u2022\tThe rank.\n\u2022\tThe HCC.\nFor comorbid CCs that do not match to Table HCC\u2014Rank, use the comorbid CC as the HCC and assign a rank of 1.\nNote: One comorbid CC can map to multiple HCCs; each HCC can have one or more comorbid CCs.",
        "step 4": "Assess each ranking group separately and select only the highest ranked HCC in each ranking group using the Rank column (1 is the highest rank possible).\nDrop all other HCCs in each ranking group, and de-duplicate the HCC list if necessary.",
        "step 5": "Identify combination HCCs listed in Table HCC\u2014Comb.\nSome combinations suggest a greater amount of risk when observed together. For example, when diabetes and CHF are present, an increased amount of risk is evident. Additional HCCs are selected to account for these relationships.\nCompare each stay\u2019s list of unique HCCs to those in the HCC column in Table HCC\u2014Comb and assign any additional HCC conditions.\nFor fully nested combinations (e.g., the diabetes/CHF combination is nested in the diabetes/ CHF/renal combination), use only the more comprehensive pattern. In this example, only the diabetes/CHF/renal combination is counted.\nFor overlapping combinations (e.g., the CHF, COPD combination overlaps the CHR/renal/ diabetes combination), use both sets of combinations. In this example, both CHF/COPD and CHF/renal/diabetes combinations are counted.\nBased on the combinations, a member can have none, one or more of these added HCCs."
    },
    "Potentially Harmful Drug-Disease Interactions in the Elderly (DDE) - Administrative Specification": {
        "step 1": "Identify members who had an accidental fall or a hip fracture. Members with either of the following on or between January 1 of the year prior to the measurement year and\nDecember 1 of the measurement year meet criteria:\n\u2022\tAn accidental fall (Falls Value Set).\n\u2022\tAn outpatient visit (Outpatient Value Set), an observation visit (Observation Value Set), an ED visit (ED Value Set), a nonacute inpatient encounter (Nonacute Inpatient Value Set) or an acute inpatient encounter (Acute Inpatient Value Set) with a hip fracture (Hip Fractures Value Set).\nIdentify the IESD for each member.",
        "step 2": "Required Exclusions\tExclude members with a diagnosis of psychosis (Psychosis Value Set), schizophrenia (Schizophrenia Value Set), bipolar disorder (Bipolar Disorder Value Set) or seizure disorder (Seizure Disorders Value Set) on or between January 1 of the year prior to the measurement year and December 1 of the measurement year."
    },
    "Potentially Harmful Drug-Disease Interactions in the Elderly (DDE) - eligible population": {
        "step 1": "Identify members who had an accidental fall or a hip fracture. Members with either of the following on or between January 1 of the year prior to the measurement year and\nDecember 1 of the measurement year meet criteria:\n\u2022\tAn accidental fall (Falls Value Set).\n\u2022\tAn outpatient visit (Outpatient Value Set), an observation visit (Observation Value Set), an ED visit (ED Value Set), a nonacute inpatient encounter (Nonacute Inpatient Value Set) or an acute inpatient encounter (Acute Inpatient Value Set) with a hip fracture (Hip Fractures Value Set).\nIdentify the IESD for each member.",
        "step 2": "Required Exclusions\tExclude members with a diagnosis of psychosis (Psychosis Value Set), schizophrenia (Schizophrenia Value Set), bipolar disorder (Bipolar Disorder Value Set) or seizure disorder (Seizure Disorders Value Set) on or between January 1 of the year prior to the measurement year and December 1 of the measurement year."
    },
    "Prenatal and Postpartum Care (PPC) - Administrative Specification": {
        "step 1": "Determine enrollment status during the first trimester. For all women in the eligible population, identify those who were enrolled on or before 280 days prior to delivery (or estimated date of delivery [EDD]). For these women, proceed to step 2.\nFor women not enrolled on or before 280 days prior to delivery (or EDD), who were therefore pregnant at the time of enrollment, proceed to step 3.",
        "step 2": "Determine continuous enrollment for the first trimester. Identify women from step 1 who were continuously enrolled during the first trimester (176\u2013280 days prior to delivery [or EDD]), with no gaps in enrollment. For these women, determine numerator compliance using the decision rules for Identifying Prenatal Care For Women Continuously Enrolled During the First Trimester.\nFor women who were not continuously enrolled during the first trimester (e.g., had a gap between 176 and 280 days before delivery), proceed to step 3.",
        "step 3": "Determine the start date of the last enrollment segment (i.e., the enrollment segment during the pregnancy with the start date that is closest to the delivery date).\nFor women whose last enrollment started on or between 219 and 279 days before delivery, proceed to step 4.\nFor women whose last enrollment started less than 219 days before delivery, proceed to step 5.",
        "step 4": "Determine numerator compliance. If the last enrollment segment started on or between 219 and 279 days before delivery, determine numerator compliance using the instructions for Identifying Prenatal Care for Women Not Continuously Enrolled During the First Trimester and find a visit between the last enrollment start date and 176 days before delivery.",
        "step 5": "Determine numerator compliance. If the last enrollment segment started less than 219 days before delivery (i.e., between 219 days before delivery and the day of delivery), determine numerator compliance using the instructions for Identifying Prenatal Care for Women Not Continuously Enrolled During the First Trimester and find a visit within 42 days after enrollment."
    },
    "Prenatal and Postpartum Care (PPC) - Eligible Population": {
        "step 1": "Identify deliveries. Identify all women with a delivery between November 6 of the year prior to the measurement year and November 5 of the measurement year. Either of the following meets criteria:\n\u2022\tA delivery (Deliveries Value Set).\n\u2022\tA delivery on an infant claim (Deliveries Infant Record Value Set), where the organization can link infant and mother records.",
        "step 2": "Exclude non-live births (Non-live Births Value Set).",
        "step 3": "Identify continuous enrollment. Determine if enrollment was continuous between 43 days prior to delivery and 56 days after delivery, with no gaps."
    },
    "Use of Appropriate Medications for People With Asthma (ASM) - Eligible Population": {
        "step 1": "Identify members as having persistent asthma who met at least one of the following criteria during both the measurement year and the year prior to the measurement year. Criteria need not be the same across both years.\n\u2022\tAt least one ED visit (ED Value Set), with a principal diagnosis of asthma (Asthma Value Set).\n\u2022\tAt least one acute inpatient encounter (Acute Inpatient Value Set), with a principal diagnosis of asthma (Asthma Value Set).\n\u2022\tAt least four outpatient visits (Outpatient Value Set) or observation visits (Observation Value Set) on different dates of service, with any diagnosis of Asthma (Asthma Value Set) and at least two asthma medication dispensing events (Table ASM-C). Visit type need not be the same for the four visits.\n\u2022\tAt least four asthma medication dispensing events (Table ASM-C).",
        "step 2": "A member identified as having persistent asthma because of at least four asthma medication dispensing events, where leukotriene modifiers were the sole asthma medication dispensed in that year, must also have at least one diagnosis of asthma (Asthma Value Set) during the same year as the leukotriene modifier (i.e., the measurement year or the year prior to the measurement year).",
        "step 3": "Required exclusions\tExclude members who had any diagnosis from any of the following value sets, any time during the member\u2019s history through December 31 of the measurement year:\n\u2022\tEmphysema Value Set.\n\u2022\tOther Emphysema Value Set.\n\u2022\tCOPD Value Set.\n\u2022\tObstructive Chronic Bronchitis Value Set.\n\u2022\tChronic Respiratory Conditions Due To Fumes/Vapors Value Set.\n\u2022\tCystic Fibrosis Value Set.\n\u2022\tAcute Respiratory Failure Value Set."
    },
    "Use of First-Line Psychosocial Care for Children and Adolescents on Antipsychotics (APP) - Eligible Population ": {
        "step 1": "Identify all members in the specified age range who were dispensed an antipsychotic medication (Table APP\u2013A) during the Intake Period.",
        "step 2": "Test for Negative Medication History. For each member identified in step 1, test each antipsychotic prescription for a Negative Medication History. The IPSD is the dispensing date of the earliest antipsychotic prescription in the Intake Period with a Negative Medication History.",
        "step 3": "Calculate continuous enrollment. Members must be continuously enrolled for 120 days (4 months) prior to the IPSD through 30 days after the IPSD.",
        "step 4": "Required exclusions\tExclude members for whom first-line antipsychotic medications may be clinically appropriate. Any of the following during the measurement year meet criteria:\n\u2022\tAt least one acute inpatient encounter with a diagnosis of schizophrenia, bipolar disorder or other psychotic disorder during the measurement year. Any of the following code combinations meet criteria:\n\u2013\tBH Stand Alone Acute Inpatient Value Set with Schizophrenia Value Set.\n\u2013\tBH Stand Alone Acute Inpatient Value Set with Bipolar Disorder Value Set.\n\u2013\tBH Stand Alone Acute Inpatient Value Set with Other Psychotic Disorders Value Set.\n\u2013\tBH Acute Inpatient Value Set with BH Acute Inpatient POS Value Set and Schizophrenia Value Set.\n\u2013\tBH Acute Inpatient Value Set with BH Acute Inpatient POS Value Set and Bipolar Disorder Value Set.\n\u2013\tBH Acute Inpatient Value Set with BH Acute Inpatient POS Value Set and Other Psychotic Disorders Value Set.\n\u2022\tAt least two visits in an outpatient, intensive outpatient or partial hospitalization setting, on different dates of service, with a diagnosis of schizophrenia, bipolar disorder or other psychotic disorder during the measurement year. Any of the following code combinations meet criteria:\n\u2013\tBH Stand Alone Outpatient/PH/IOP Value Set with Schizophrenia Value Set.\n\u2013\tBH Outpatient/PH/IOP Value Set with BH Outpatient/PH/IOP POS Value Set and Schizophrenia Value Set.\n\u2013\tBH Stand Alone Outpatient/PH/IOP Value Set with Bipolar Disorder Value Set.\n\u2013\tBH Outpatient/PH/IOP Value Set with BH Outpatient/PH/IOP POS Value Set and Bipolar Disorder Value Set.\n\u2013\tBH Stand Alone Outpatient/PH/IOP Value Set with Other Psychotic Disorders Value Set.\n\u2013\tBH Outpatient/PH/IOP Value Set with BH Outpatient/PH/IOP POS Value Set and Other Psychotic Disorders Value Set."
    },
    "Use of Imaging Studies for Low Back Pain (LBP) - Eligible Population": {
        "step 1": "Identify all members in the specified age range who had any of the following during the Intake Period:\n\u2022\tOutpatient visit (Outpatient Value Set), with a principal diagnosis of low back pain (Low Back Pain Value Set).\n\u2022\tObservation visit (Observation Value Set), with a principal diagnosis of low back pain (Low Back Pain Value Set).\n\u2022\tED visit (ED Value Set), with a principal diagnosis of low back pain (Low Back Pain Value Set). Do not include ED visits that result in an inpatient admission.\n\u2022\tOsteopathic manipulative treatment (Osteopathic Manipulative Treatment Value Set), with a principal diagnosis of low back pain (Low Back Pain Value Set).",
        "step 2": "Determine the IESD. For each member identified in step 1, determine the earliest episode of low back pain. If the member had more than one encounter, include only the first encounter.",
        "step 3": "Test for Negative Diagnosis History. Exclude members with a diagnosis of low back pain (Low Back Pain Value Set) during the 180 days (6 months) prior to the IESD.",
        "step 4": "Required exclusions\tExclude any member who had a diagnosis for which imaging is clinically appropriate. Any of the following meet criteria:\n\u2022\tCancer. Cancer any time during the member\u2019s history through 28 days after the IESD. Any of the following meet criteria:\n\u2013\tMalignant Neoplasms Value Set.\n\u2013\tOther Neoplasms Value Set.\n\u2013\tHistory of Malignant Neoplasm Value Set.\n\u2022\tRecent trauma. Trauma (Trauma Value Set) any time during the 12 months (1 year) prior to the IESD through 28 days after the IESD.\n\u2022\tIntravenous drug abuse. IV drug abuse (IV Drug Abuse Value Set) any time during the 12 months (1 year) prior to the IESD through 28 days after the IESD.\n\u2022\tNeurologic impairment. Neurologic impairment (Neurologic Impairment Value Set) any time during the 12 months (1 year) prior to the IESD through 28 days after the IESD.",
        "step 5": "Calculate and continuous enrollment. Members must be continuously enrolled for 180 days (6 months) prior to the IESD through 28 days after the IESD."
    },
    "Use of Multiple Concurrent Antipsychotics in Children and Adolescents (APC) - Administrative Specification": {
        "step 1": "For each member, by Drug ID, identify all drug events, start dates and end dates (identified in step 4 of the event/diagnosis criteria used to identify the eligible population [denominator]).",
        "step 2": "Identify concurrent antipsychotic medication treatment events as follows.\nFor each member, identify the first day during the measurement year where the member was being treated with two or more different antipsychotic medications (use the Drug ID to identify different drugs); this is the concurrent antipsychotic medication treatment event start date.\nBeginning with (and including) the start date, identify the number of consecutive days where the member remains on two or more different antipsychotic medications. If the number of days \u226590 days, the member is numerator compliant.\nIf the number of consecutive days on multiple antipsychotic medications is <90 days, identify the end date and identify the next day during the measurement year where the member was being treated with two or more different antipsychotic medications. If the number of days between the end date and the next start date is \u226415 days, include the days in the concurrent antipsychotic medication treatment event (concurrent antipsychotic medication treatment events allow for a 15-day gap).\nIf the number of days between the end date and the next start date exceeds 15 days, end the event; using the new start date, continue to assess for concurrent antipsychotic medication treatment events.\nContinue this process until the number of concurrent antipsychotic medication treatment days is \u226590 consecutive days (i.e., the member is numerator compliant) or until the measurement year is exhausted (i.e., no concurrent antipsychotic medication treatment events were identified during the measurement year)."
    },
    "Use of Multiple Concurrent Antipsychotics in Children and Adolescents (APC) - Eligible Population": {
        "step 1": "Identify members in the specified age range who were dispensed an antipsychotic medication (Table APC-A) during the measurement year.",
        "step 2": "Calculate continuous enrollment. The member must be continuously enrolled during the measurement year.",
        "step 3": "For each member, identify all antipsychotic medication dispensing events (prescriptions) during the measurement year.",
        "step 4": "Identify start and end dates for drug events. Drug events are defined separately by drug using the Drug ID field in the NDC list.\nFor each drug ID, sort dispensing events chronologically by dispense date. If there is more than one prescription for the same medication dispensed on the same day, use only the prescription with the longest days supply in the calculation.\nStarting with the first prescription in the measurement year determine if there is a second dispense date with the same Drug ID.\n\u2022\tIf there is no second dispensing event with the same Drug ID, the start date is the first prescription\u2019s dispense date and the end date is the start date plus the days supply minus one. For example, a January 1 prescription with a 30 days supply has an end date of January 30.\n\u2022\tIf there is a second dispensing event with the same Drug ID, determine if there are gap days (a 32-day gap is allowed). Calculate the number of days between (but not including) the first prescription\u2019s dispense date and the second prescription\u2019s dispense date. If the number of days is less than or equal to the first prescription\u2019s days supply plus 32 days, the gap is less than or equal to 32 days and is allowed. The start date is the first prescription\u2019s dispense date and the end date is the second prescription\u2019s dispense date plus days supply minus one. Continue assessing all subsequent dispensing events with allowable gaps for the same Drug ID and adjust end dates as needed.\n\u2013\tFor example, a member has two dispensing events with the same Drug ID. The first is on July 1, with a 30 days supply. The second is on September 1, with a 30 days supply. The number of days between (but not including) the dispense dates is 61 (July 2\u2013August 31).The gap is allowed because 61 is less than the first prescription\u2019s days supply plus 32 days (30 + 32 = 62). The start date is July 1 and the end date is September 30.\n\u2022\tIf there is a second dispensing event with the same Drug ID and there is a gap that exceeds the allowable gap, assign an end date for this drug event and follow the beginning of step 4 for the remaining dispensing events. A member can have multiple start and end dates per Drug ID during the measurement year.\nContinue assessing each dispensed prescription for each Drug ID until all dispensing events are exhausted. If a dispensing event goes beyond December 31 of the measurement year, assign the end date as December 31.",
        "step 5": "For each member, identify those with \u226590 consecutive treatment days.\nFor each member, using the start and end dates from all drug events identified in step 4 (which may include events for the same or different medications and may include events with allowable gaps), determine all calendar days covered by at least one antipsychotic medication. If there were \u226590 consecutive calendar days, include the member in the measure."
    },
    "Use of Spirometry Testing in the Assessment and Diagnosis of COPD (SPR) - Eligible Population": {
        "step 1": "Identify all members who had an outpatient visit (Outpatient Value Set), an observation visit (Observation Value Set), an ED visit (ED Value Set) or an acute inpatient encounter (Acute Inpatient Value Set), during the Intake Period, with any diagnosis of COPD (COPD Value Set), emphysema (Emphysema Value Set) or chronic bronchitis (Chronic Bronchitis Value Set).\nIf the member had more than one eligible visit, include only the first visit.",
        "step 2": "Test for Negative Diagnosis History. Exclude members who had an outpatient visit (Outpatient Value Set), an observation visit (Observation Value Set), an ED visit (ED Value Set) or an acute inpatient encounter (Acute Inpatient Value Set) during the 730 days (2 years) prior to the IESD, with a diagnosis of COPD (COPD Value Set), emphysema (Emphysema Value Set) or chronic bronchitis (Chronic Bronchitis Value Set).\nFor an acute inpatient IESD, use the date of admission to determine the Negative Diagnosis History.",
        "step 3": "Calculate continuous enrollment. Members must be continuously enrolled in the organization 730 days (2 years) prior to the IESD through 180 days (6 months) after the IESD."
    },
    "Weeks of Pregnancy at Time of Enrollment (WOP) - Administrative Specification": {
        "step 1": "Prior to pregnancy. Identify all women whose most recent date of enrollment in the organization was more than 40 weeks (280 days or more prior to delivery) prior to the delivery date. These women will be included in the \u22640 weeks row of Table WOP-1. Include women even if they had a premature birth.",
        "step 2": "Premature births. For women with a delivery date \u226440 weeks (fewer than 280 days prior to delivery) after enrollment in the organization, identify deliveries that resulted in a premature birth (Premature Births Value Set).\nFor women who had a premature birth, use either the EDD or gestational age of the fetus recorded in delivery records or the last menstrual period noted in the patient\u2019s prenatal care record to estimate the weeks of pregnancy at enrollment in the organization. If these are not available, include these women in the Unknown category.",
        "step 3": "Assume a full-term pregnancy for all remaining women (i.e., those not enrolled in the organization more than 40 weeks prior to the delivery date, and for whom there is no indication of a premature birth). For these women, the weeks of pregnancy at enrollment is determined by subtracting the number of weeks of enrollment in the organization prior to delivery from 40 weeks. Calculate the number of women in each remaining category:\n\u2022\t1\u201312 weeks of pregnancy (279\u2013196 days prior to delivery).\n\u2022\t13\u201327 weeks of pregnancy (195\u201391 days prior to delivery).\n\u2022\t28 or more weeks of pregnancy (\u226490 days prior to delivery)."
    },
    "Weeks of Pregnancy at Time of Enrollment (WOP) - Eligible Population": {
        "step 1": "Identify deliveries. Identify all women with a delivery during the measurement year. Either of the following meets criteria:\n\u2022\tA delivery (Deliveries Value Set).\n\u2022\tA delivery on an infant claim (Deliveries Infant Record Value Set), where the organization can link infant and mother records.",
        "step 2": "Exclude non-live births (Non-live Births Value Set)."
    }
}


def merge_dict(d):
    '''把dict中的多个key, value对按照格式组合起来, 用于GUI中最后结果的显示'''
    res = list()
    for k,v in d.iteritems():
        res.append( k + '\n' + v + '\n')
    return '\n'.join(res)

def search_name(name):
    '''主要功能函数，用于搜索key'''
    if name not in data:
        return "%s doesn't exists" % name
    else:
        return merge_dict( data[name] ) 

def drag_down_menu(data):
    '''generate drag down menu for RUBY web developer'''
    keys = list(data.keys())
    keys.sort()
    with open('drag_down.txt', 'wb') as f:
        ctt = list()
        for name in keys:
            ctt.append('"%s",' % name)
    f.write('\n'.join(ctt))
    
if __name__ == '__main__':
    ''' unit test '''
    print search_name('Weeks of Pregnancy at Time of Enrollment (WOP) - Eligible Population')
    drag_down_menu(data)